### ISSUE TITLE
Frequent disconnects from macOS Sierra 10.12.2 to FreeBSD 11, using iSCSIInitiator 1.0.0-beta5

### ISSUE THREAD

**Issue by jeremyandrews** [iscsi-osx/iSCSIInitiator#81] opened 2017-01-03 08:46 UTC
I'm testing out iSCSIInitiator on macOS Sierra 10.12.2, connecting to a Target on a FreeBSD 11.0-RELEASE-p2 kernel. I've successfully used this target with a fairly basic ctld configuration using a different Initiator. The target volume is hosted as a zvol.

I see very slow performance and frequent disconnects.

I login successfully as follows:

```
$ iscsictl login iqn.2017-01.fosciana.albert:target0
Attached iqn.2017-01.fosciana.albert:target0 <scsi domain 0, target 0>
	FREEBSD CTLDISK 0001
	Serial Number MYSERIAL   0
	lun 0: type 0x00 (Block device)
$ iscsictl list luns
iqn.2017-01.fosciana.albert:target0 <scsi domain 0, target 0>
	FREEBSD CTLDISK 0001
	Serial Number MYSERIAL   0
	lun 0: type 0x00 (Block device)
		disk2: 1.1 TB (2147483648 512 byte blocks)
$ diskutil list disk2
/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.1 TB     disk2
   1:                        EFI EFI                     209.7 MB   disk2s1
   2:                  Apple_HFS Backups                 1.1 TB     disk2s2
```

I then configure Time Machine to backup to this device. After a minute or two, I get a warning about ejecting the drive and I see that it's no longer mounted.

I captured iSCSI traffic with wireshark.
[iSCSIdisconnect-2.pcapng.gz](https://github.com/iscsi-osx/iSCSIInitiator/files/681903/iSCSIdisconnect-2.pcapng.gz)

Ultimately the drive re-connects, and I see the same LUN twice:

```
$ iscsictl list luns
iqn.2017-01.fosciana.albert:target0 <scsi domain 0, target 0>
	FREEBSD CTLDISK 0001
	Serial Number MYSERIAL   0
	lun 0: type 0x00 (Block device)
		disk2: 1.1 TB (2147483648 512 byte blocks)
iqn.2017-01.fosciana.albert:target0 <scsi domain 0, target 0>
	FREEBSD CTLDISK 0001
	Serial Number MYSERIAL   0
	lun 0: type 0x00 (Block device)
		disk2: 1.1 TB (2147483648 512 byte blocks)
```

At this point I can't 'iscsictl logout' and I've found that only rebooting will get things back to a sane state.

**Comment by nsinenian** [comment] 2017-01-03 08:52
Strange indeed. Can you please post the iSCSI traffic if its not too big? I'm interested in (1) the parameters that are negotiated upon login (so the first few packets) and the last ~1-2 minutes before a disconnect in order to understand why this is happening.

**Comment by jeremyandrews** [comment] 2017-01-03 08:55
The full wireshark log is attached above now, all traffic on port 3260 from before login to after the failure.

**Comment by nsinenian** [comment] 2017-01-03 09:15
Thanks. From what I remember, ctld on FreeBSD outputs console messages when users login or when connections are dropped. Can you also please check to see if there is any such output when a drop occurs?

**Comment by jeremyandrews** [comment] 2017-01-03 09:21
I see two messages:

```
WARNING: 10.10.6.5 (iqn.2015-01.com.localhost): connection error; dropping connection
WARNING: 10.10.6.5 (iqn.2015-01.com.localhost): no ping reply (NOP-Out) after 5 seconds; dropping connection
```

**Comment by jeremyandrews** [comment] 2017-01-03 09:25
I see there's a debug mode; I'll restart in debug mode and see if I can get any more useful information.

**Comment by nsinenian** [comment] 2017-01-03 09:26
Actually this is quite helpful. I thought NOP outs were being sent, but there may be a bug there in the initiator code. Interesting that it is specific to BSD.  

The TCP traffic shows no errors or problems. I think its simply a that the target pings the initiator using NOPs and the initiator doesn't respond (even though it is respond to other commands and exchanging data).

**Comment by jeremyandrews** [comment] 2017-01-03 09:28
Great! Because it exits debug mode after I make an actual connection. In case this is useful, this is all the debug I captured:

```
Starting ctld.
ctld: obtaining previously configured CTL luns from the kernel
ctld: CTL port 0 "ioctl" wasn't managed by ctld; 
ctld: CTL port 1 "tpc" wasn't managed by ctld; 
ctld: CTL port 2 "camsim" wasn't managed by ctld; 
ctld: obtaining configuration from /etc/ctl.conf
ctld: /etc/ctl.conf is world-readable
ctld: auth-group "default" not defined; going with defaults
ctld: portal-group "default" not defined; going with defaults
ctld: opening pidfile /var/run/ctld.pid
ctld: adding lun "iqn.2017-01.fosciana.albert:target0,lun,0"
ctld: adding port "pg0-iqn.2017-01.fosciana.albert:target0"
ctld: not listening on portal-group "default", not assigned to any target
ctld: listening on 0.0.0.0, portal-group "pg0"
ctld: incoming connection; not forking due to -d flag
ctld: accepted connection from 10.10.6.5; portal group "pg0"
ctld: 10.10.6.5: setting session timeout to 60 seconds
ctld: 10.10.6.5: Capsicum capability mode enabled
ctld: 10.10.6.5: beginning Login Phase; waiting for Login PDU
ctld: 10.10.6.5: key received: "SessionType=Normal"
ctld: 10.10.6.5: key received: "InitiatorAlias=default"
ctld: 10.10.6.5: key received: "InitiatorName=iqn.2015-01.com.localhost"
ctld: 10.10.6.5: key received: "TargetName=iqn.2017-01.fosciana.albert:target0"
ctld: 10.10.6.5: key received: "AuthMethod=None,CHAP"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): initiator requests to connect to target "iqn.2017-01.fosciana.albert:target0"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): CHAP authentication required
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "AuthMethod=CHAP"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "TargetPortalGroupTag=257"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): beginning CHAP authentication; waiting for CHAP_A
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "CHAP_A=5"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): sending CHAP_C, binary challenge size is 1024 bytes
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "CHAP_A=5"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "CHAP_I=18"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "CHAP_C=0xfaa5f27c7e7e179fe538ec85474033b3597880085bec7e7714818bab4ca9cb1bb1232079dc9ce5d4872551997e14a45712691be364d1e026445427454b91dfb6d88445d2b6a9e4c3f80862923813d2ca40ed016b6a66b6c3f73b188847a08262812d10d9b454dcda23f5a00a92eb026cfb17d3536b3c36f4e3cee575a6586578b8c86ac4447d2185136b7f2daf8d3f6d82ba94ceb6f14572d096ad2801de9c1256ce807d964876051f98346f92c0ed4b043c1cac48cd601911e30559f8fb8ace12837654215bf973ffca838ae8f67fa7da5dd9f3bb2e91bac7b3f458db426c0aee25a4a4def3562db5defb064acfa069cc01f2cfebee0654fe3705753c9c562815fe6df5ee08e9b925613af40643e5cea460f885558c486ad7c13618131cb4c75cf39ca342f3f84ad80ddd17d42f5389465a2e1020e424229498f148c63c1b4fdc04050f2ca5e963bbede737c0926922cc2b0c09b637c66dbaaa15d278dc41b20e26eb261249609ff671b3c47fbce4689c6d90408b412174e88e9cd4b9646069849bbd9d33a1f840c2c9b4383ffe85b5b0fe0653fbd597be509c7717c4d45e7c3750cd3c5930166d46ebfd269b860c046a1e25c0a678121720679541eecd87422ec476ab02e440680d236940ffbdc8b3206a173e7b5482c1d7f8af26e25d4bbb454bc0ea62483458096895a5470e999a4fa936f0
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): waiting for CHAP_N/CHAP_R
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "CHAP_N=jandrews"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "CHAP_R=0xef2657731d7746fd01b842176a74e434"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): authentication succeeded for user "jandrews"; transitioning to Negotiation Phase
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "CHAP_N=jandrews"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "CHAP_R=0xef2657731d7746fd01b842176a74e434"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): initiator did not request target authentication
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): MaxRecvDataSegment kernel limit is 131072
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): beginning operational parameter negotiation; waiting for Login PDU
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "HeaderDigest=None"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DefaultTime2Wait=2"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "ErrorRecoveryLevel=0"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DataPDUInOrder=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DataDigest=None"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "ImmediateData=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxConnections=1"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "InitialR2T=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxBurstLength=262144"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DefaultTime2Retain=20"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "FirstBurstLength=65536"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DataSequenceInOrder=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxOutstandingR2T=1"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxRecvDataSegmentLength=8192"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): initiator prefers not to do header digest; we'll comply
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "HeaderDigest=None"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DefaultTime2Wait=2"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "ErrorRecoveryLevel=0"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DataPDUInOrder=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): initiator prefers not to do data digest; we'll comply
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DataDigest=None"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "ImmediateData=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxConnections=1"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "InitialR2T=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxBurstLength=262144"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DefaultTime2Retain=0"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "FirstBurstLength=65536"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DataSequenceInOrder=Yes"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxOutstandingR2T=1"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxRecvDataSegmentLength=131072"
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): operational parameter negotiation done; transitioning to Full Feature Phase
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): connection handed off to the kernel
ctld: 10.10.6.5 (iqn.2015-01.com.localhost): nothing more to do; exiting
```

**Comment by jeremyandrews** [comment] 2017-01-03 09:51
I enabled `debug 2` ( https://www.freebsd.org/cgi/man.cgi?query=ctl&sektion=4 ) and now everything seems to work. My time machine backup has transferred >1 GB of data without errors (whereas before it timed out after just a few K).

I don't see anything special in the new debug, but here it is if it's useful:
```
Jan  3 09:45:56 albert ctld[19470]: incoming connection; forking child process #0
Jan  3 09:45:56 albert ctld[19712]: accepted connection from 10.10.6.5; portal group "pg0"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: setting session timeout to 60 seconds
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: Capsicum capability mode enabled
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: beginning Login Phase; waiting for Login PDU
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: key received: "SessionType=Discovery"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: key received: "InitiatorAlias=default"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: key received: "InitiatorName=iqn.2015-01.com.localhost"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5: key received: "AuthMethod=None"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): initiator requests discovery session; auth-group "no-authentication"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): authentication not required
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "AuthMethod=None"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): beginning operational parameter negotiation; waiting for Login PDU
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "HeaderDigest=None"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DefaultTime2Wait=2"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "ErrorRecoveryLevel=0"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DataPDUInOrder=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DataDigest=None"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "ImmediateData=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxConnections=1"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "InitialR2T=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxBurstLength=262144"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DefaultTime2Retain=20"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "FirstBurstLength=65536"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "DataSequenceInOrder=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxOutstandingR2T=1"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "MaxRecvDataSegmentLength=8192"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): discovery session; digests disabled
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "HeaderDigest=None"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DefaultTime2Wait=2"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "ErrorRecoveryLevel=0"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DataPDUInOrder=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): discovery session; digests disabled
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DataDigest=None"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): discovery session; ImmediateData irrelevant
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "ImmediateData=Irrelevant"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxConnections=1"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "InitialR2T=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxBurstLength=262144"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DefaultTime2Retain=0"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "FirstBurstLength=65536"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "DataSequenceInOrder=Yes"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxOutstandingR2T=1"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "MaxRecvDataSegmentLength=131072"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): operational parameter negotiation done; transitioning to Full Feature Phase
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): beginning discovery session; waiting for Text PDU
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key received: "SendTargets=All"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): key to send: "TargetName=iqn.2017-01.fosciana.albert:target0"
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): done sending targets; waiting for Logout PDU
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): discovery session done
Jan  3 09:45:56 albert ctld[19712]: 10.10.6.5 (iqn.2015-01.com.localhost): nothing more to do; exiting
Jan  3 09:45:56 albert ctld[19470]: child process 19712 terminated gracefully
```

**Comment by nsinenian** [comment] 2017-01-03 12:01
There may be a latent bug in the initiator, but I believe there may be an issue with the BSD target. According to RFC7143:

"Upon receipt of a NOP-In with the Target Transfer Tag set to a valid value (not the reserved value 0xffffffff), the initiator MUST respond with a NOP-Out."

The problem is that the target sends NOP-In to the initiator with the target transfer tag set to the reserved value. In this case, according to the standard, the initiator need not respond. Please verify/confirm. I suspect that many initiators simply respond regardless, which is why they work.

**Comment by jeremyandrews** [comment] 2017-01-03 12:17
Any idea why enabling debug on the Target would fix this? Would a tcpdump while debug is enabled be useful?

Or are you suggesting I re-install the other Initiator I used previously that worked and capture a new tcpdump? How long of a capture would I need?

**Comment by nsinenian** [comment] 2017-01-03 12:21
> Any idea why enabling debug on the Target would fix this? 

I suppose in debug mode the target ignores the fact that the initiator isn't responding. But I can't be sure.

> Would a tcpdump while debug is enabled be useful?

It might be. If its too much trouble don't bother. Otherwise capture some traffic. Only capture after the connection is up and running, and then we only need to see a NOP-In and a NOP-out. If you type in "iscsi" in the filter box for Wireshark you'll see the iSCSI packet (PDU) types.

> Or are you suggesting I re-install the other Initiator I used previously that worked and capture a new tcpdump? How long of a capture would I need?

Again, if you have the time, this would be helpful to the debugging process, and I just left a report for the FreeBSD guys. Same as the above, you only need to capture a NOP-Out/NOP-In combination, which I suspect will occur within a minute or two into the capture.

**Comment by jeremyandrews** [comment] 2017-01-03 13:52
With debug enabled and the iSCSI connection working (a backup is running), I filtered to only see `iscsi.opcode == 0x20 || iscsi.opcode == 0x0`. This ONLY shows me the Target sending `NOP In` repeatedly. If I filter to only `iscsi.opcode == 0x0` I see nothing at all. I never see the iSCSIInitiator sending a NOP.

**Comment by jeremyandrews** [comment] 2017-01-03 14:39
I uninstalled iSCSIInitiator-1.0.0-beta5 and installed globalSAN-5.3.0.541 then started the backup again. I see drastically fewer NOP-In's in the dump, and still no NOP-Out's. Whereas w/ iSCSIInitiator I see a NOP-In sometimes several times a second, and at least once every 2-3 seconds, with globalSAN I'm often not seeing them for >30 seconds.

What debug information would you like to see?

**Comment by jeremyandrews** [comment] 2017-01-03 14:46
I'm not sure this is enough by itself, but here's the pcap filtered by `iscsi.opcode == 0x20 || iscsi.opcode == 0x0` for my two different tests.

[iSCSIInitiator-NOP.pcap.gz](https://github.com/iscsi-osx/iSCSIInitiator/files/682428/iSCSIInitiator-NOP.pcap.gz)
[globalSAN-NOP.pcap.gz](https://github.com/iscsi-osx/iSCSIInitiator/files/682433/globalSAN-NOP.pcap.gz)

I'll collect a shorter sample w/ all data w/ the globalSAN driver and upload next.

**Comment by jeremyandrews** [comment] 2017-01-03 14:57
It took me several tries to get a short sample with a NOP, but the attached includes both the login and a NOP-In from the Target.

[globalSAN-connect.pcap.gz](https://github.com/iscsi-osx/iSCSIInitiator/files/682466/globalSAN-connect.pcap.gz)

**Comment by nsinenian** [comment] 2017-01-03 15:25
Did you capture that last one with debug mode on or off on the target?

**Comment by jeremyandrews** [comment] 2017-01-03 15:26
It was still on.

**Comment by nsinenian** [comment] 2017-01-03 15:32
It appears (in both the globalSAN and the iSCSIInitiator) that the way the transfer tags are marked by the target flip-flop in debug mode. In one case, the target expects no response from the initiator, in the other, it does expect a response, and this expectation is the opposite of my interpretation of the standard. Let me see if there are updates or errata on this that I missed, and what the BSD dev team thinks.

I haven't heard reports of this happening with other targets, but people I've heard from are mainly using various Linux-based targets. That's why I'm a bit suspicious of BSD's implementation, but it could very well be that I got it backwards. Will get back to you -- these tests were very helpful.

**Comment by jeremyandrews** [comment] 2017-01-03 15:40
Great! Thanks for being so responsive and helpful!

If there's any value, I disabled debug on the Target and captured another log of connecting and some data transfer. I did this a dozen times and never once saw a NOP. Here's my final attempt which includes a login and a logout, but still no NOP -- with the iSCSIInitiator driver we always see lots of NOPs.

[globalSAN-connect2.pcap.gz](https://github.com/iscsi-osx/iSCSIInitiator/files/682532/globalSAN-connect2.pcap.gz)

**Comment by nsinenian** [comment] 2017-02-14 15:21
I've tried to reproduce this problem using a VM and I have found nothing so far -- I can't seem to make the target drop the connection. Can you check the output for:

sysctl kern.cam.ctl.iscsi.ping_timeout

and let me know what it is?

**Comment by jeremyandrews** [comment] 2017-02-14 16:04
`# sysctl kern.cam.ctl.iscsi.ping_timeout
kern.cam.ctl.iscsi.ping_timeout: 5`

**Comment by nsinenian** [comment] 2017-02-14 16:10
Thanks - can you please trying increasing this value (to say, 60) to see if that addresses the problem? 

I am wondering if it simply takes this initiator longer to respond to the pings than say, globalSAN because of the way requests are queued/processed.

If that doesn't do anything, please try setting this value to 0 to disable NOPs from the target and let me know if the problem goes away (it will confirm that the issue is in fact a missing/delayed NOP from the initiator.

**Comment by jeremyandrews** [comment] 2017-02-14 16:14
I will retest in a few days (I'm currently traveling).

**Comment by jeremyandrews** [comment] 2017-02-21 11:33
After increasing ping_timeout, everything seems to work perfectly. I successfully completed a 43GB backup. Are there any downsides to this configuration?

`# sysctl kern.cam.ctl.iscsi.ping_timeout
kern.cam.ctl.iscsi.ping_timeout: 60`

**Comment by nsinenian** [comment] 2017-02-22 16:07
The downside is that if something goes wrong with the connection the target won't realize it for a whole minute. You may have to wait a minute to get things going again. I don't think this is a good permanent solution, but gives us a clue about the problem.

Have you tried experimenting with the timeout, between 5 and 60 to determine the threshold value?

**Comment by jeremyandrews** [comment] 2017-02-24 10:34
Oddly I'm unable to duplicate the errors I was seeing before. I just ran a 6GB backup w/o any problems, with the default ping_timeout of 5 seconds. I'm still on the same version of the FreeBSD kernel, 11.0-RELEASE-p2. I have applied updates to the Mac OS X laptop where I've been running the tests from.

I have no idea what fixed things, but I guess this can just be closed?

**Comment by hachre** [comment] 2017-03-17 07:20
I have the same problem, same setup - also with FreeBSD as the host. It is however 11.0-RELEASE-p8 in my case. I raised the timeout to 60 and it fixed my problems as well. What's curious is I didn't have any issues running Time Machine but copying a 10 GB file via Finder reliably triggered the problem.

**Comment by nsinenian** [comment] 2017-03-19 04:53
If you're roaming and you loose connection "shortly" that may be a problem. The TCP timeout is currently set to about 1 second on the initiator side. 

Still trying to get to the bottom of this -- @jeremyandrews was unable to duplicate his problem so it's interesting that yours persists. At what point during the transfer does it reliably disconnect when transferring that 10GB file? Can you time it roughly to the second? (I want to see if it matches any other internal timeouts).

**Comment by hachre** [comment] 2017-03-19 11:37
With the timeout at 240, I finally had no issues at all. I also experimented with Roaming and can say that Roaming did not seem to cause additional issues. There's only about a 2-3 second ping timeout while Roaming (max), if a timeout happens at all. Open connections don't go into closed state while doing it. 

I tried bringing the timeout in FreeBSD back down to 60 but can no longer reproduce the issue now. It's just like jeremyandrews' case. I'm going to keep trying with the lower timeout. I currently suspect that increasing the timeout on the FreeBSD side applies instantly, but reducing it may need a reboot. That's the only explanation I have at this point for this behavior.

When I was able to reproduce it previously, I sometimes had the Finder "Copying" window open while it was copying the 8 GB file and I saw that the progress bar continued happily copying just until the moment when the drive was suddenly gone and macOS informed me that removing a drive without ejecting it was unhealthy. When this happened my iSCSI FreeBSD host had the following message in its kernel log: 
```
Mar 17 12:50:32 FreeBSD kernel: [4716] WARNING: 10.10.10.50 (iqn.2015-01.com.localhost): connection error; dropping connection
Mar 17 12:50:32 FreeBSD kernel: [4716] WARNING: 10.10.10.50 (iqn.2015-01.com.localhost): waiting for CTL to terminate 1 tasks
Mar 17 12:50:32 FreeBSD kernel: [4716] WARNING: 10.10.10.50 (iqn.2015-01.com.localhost): tasks terminated
```

I'm going to keep trying to reproduce it with the timeout back at 60 and see if I can find out why it doesn't reproduce easily.

**Comment by hachre** [comment] 2017-03-20 12:17
Another update: I have not been able to reproduce with the timeout back at the standard of 5 seconds. However I have noticed that if my Laptop really times out (because I disable the WiFi), the FreeBSD server message doesn't say `connection error; dropping connection` but instead `no ping reply (NOP-Out) after 5 seconds; dropping connection`. It now looks as if increasing the ping timeout was a placebo and didn't really do anything about the issues I had. I still don't understand where the connection errors came from, though.

**Comment by jeremyandrews** [comment] 2017-03-20 12:59
My server was fairly idle other than writing backups from my laptop. Also, during my early testing I enabled a free-trial of a commercial Initiator which had no problems at all -- this issue only happened for me with iSCSIInitiator.

I've been interested in seeing your testing, as I'm still unable to duplicate the problem that I had originally.

The only time I see a dropped connection message any more is when there are legitimate internet issues: earlier today I upgraded the firmware on my AP's, and when the one I was connected to rebooted that triggered the error. I also live in a stone house, and if I'm walking around with my laptop there's frequently not a graceful transfer between AP's which can also cause the message. When I leave my laptop plugged in and in one place, I don't see the dropped connections.

Regarding ZFS, I don't have any of those options enabled:
```
backup  compression  off       default
backup  dedup     off            default
backup  atime     off    local
```

**Comment by nsinenian** [comment] 2017-03-20 13:48
For the builds you guys are using, there's a TCP connection timeout of 1 second, a task timeout of 20 seconds (which may trigger the OS to re-issue the request a couple times before it "drops" the connection). It would be helpful to know in your situation, @hachre the details surrounding that connection error (e.g., iSCSI PDUs sent/received and which side dropped the connection). I think the first step is reproducibility. I'm running an IET target so can't test on that. I've tried all kinds of tests on a VM running BSD (no ZFS) and nothing there either.

You can use Wireshark to diagnose but it's impractical to run it the whole time just in case this pops up again. So if you guys can't reproduce, I'd suggest (if you can) building from sources and running a "debug" version that will post kernel logs. That way the instant it does happen you can send me some information. Let me know if you need help with that.

**Comment by hachre** [comment] 2017-04-15 17:14
I cannot reproduce it anymore. My FreeBSD testing host used to be a VirtualBox VM. I moved it to VMware Fusion a while later and haven't been able to reproduce the problem once since. It seems my issues had to do with the VM software.

**Comment by nsinenian** [comment] 2017-04-16 15:04
@hachre I have a feeling its something else... throughout development I have used several targets for testing. One of them has always been FreeBSD on VirtualBox, and I never had this problem. It's likely to be a corner case (obscure bug) or configuration dependent somehow.

**Comment by nsinenian** [comment] 2018-07-20 04:06
I don't know whether this has been resolved in -Beta6, but there are too many changes since then (including macOS updates). Please open a new thread if issue persists with reference to current beta/OS.

**Closed by nsinenian** 2018-07-20 04:06 UTC
