### ISSUE TITLE
iSCSI login not working

### ISSUE THREAD

**Issue by mcfu** [iscsi-osx/iSCSIInitiator#4] opened 2015-05-15 15:32 UTC
Dear all,

nice project but I'm unable to get it to work. Compiling and using the kext and binarys is working so far with one little addition: Maybe it should be mentioned that one needs to disable kext signing security if using OS X in version 10.9 and above. To do so simply set the following parameter in terminal:

##### sudo nvram boot-args=kext-dev-mode=1

and restart the machine before loading the kext.

Furthermore I noticed a little error. The hardcoded initiator-name in iSCSISession.c should be read correctly in iSCSIAuth.c (wrong variable was used here):

##### diff -uN iSCSIAuth.c.orig iSCSIAuth.c
<pre>
--- iSCSIAuth.c.orig    2015-05-15 17:07:23.557196400 +0200
+++ iSCSIAuth.c 2015-05-15 17:08:41.549346924 +0200
@@ -20,6 +20,7 @@
 extern unsigned int kiSCSISessionMaxTextKeyValuePairs;

 extern CFStringRef kiSCSIInitiatorIQN;
+extern CFStringRef kiSCSIInitiatorName;
 extern CFStringRef kiSCSIInitiatorAlias;

 /*! Helper function.  Create a null-terminated byte array that holds the
@@ -297,7 +298,7 @@
 /// TODO: fix initiator name (read from globals?)

     // Read global variables for initiator name & alias and add them to dict.
-    CFDictionaryAddValue(authCmd,kiSCSILKInitiatorName,kiSCSILKInitiatorName);
+    CFDictionaryAddValue(authCmd,kiSCSILKInitiatorName,kiSCSIInitiatorName);
     CFDictionaryAddValue(authCmd,kiSCSILKInitiatorAlias,kiSCSIInitiatorAlias);

     // Determine authentication method used and add to dictionary
@@ -456,7 +457,7 @@
     CFDictionaryAddValue(authCmd,kiSCSILKTargetName,iSCSITargetGetIQN(target));

 // TODO: grab name from the daemon / local variable?
-    CFDictionaryAddValue(authCmd,kiSCSILKInitiatorName,kiSCSILKInitiatorName);
+    CFDictionaryAddValue(authCmd,kiSCSILKInitiatorName,kiSCSIInitiatorName);
     CFDictionaryAddValue(authCmd,kiSCSILKInitiatorAlias,kiSCSIInitiatorAlias);
     CFDictionaryAddValue(authCmd,kiSCSILKAuthMethod,kiSCSILVAuthMethodAll);
</pre>

But now it's getting harder, I can't get managed to connect to my iSCSI Server. The command

##### iscsictl -add -target iqn.2015-05.com.whatever:rbd.disk1 -portal 192.168.0.1:3260

works fine. But when trying to login with command

##### iscsictl -login -target iqn.2015-05.com.whatever:rbd.disk1 -portal 192.168.0.1:3260

I just get the error message:

**Login to [ target: iqn.2015-05.com.whatever:rbd.disk1 portal: 192.168.0.1:3260 if: en0 ] failed: Unknown error occurred.**

On the server side I get the following error message:

**[16603465.600920] Unable to locate "=" separator for key, ignoring request.
[16603465.600958] iSCSI Login negotiation failed.**

I'm using the Linux iSCSI LIO (included in Kernel) implementation. Any clue what could be the problem? Sniffing with wireshark the initial iSCSI login package/handshake looks fine to me. Connecting to the target from a linux machine with iscsiadm works without any problems.

Furthermore running "iscsictl −discovery −portal ..." hangs the iscsid daemon at 100 percent cpu load. The only way to recover is to kill the process. But that wouldn't mind me for now. The more important thing is to get the login to work probably.

If you need more data from me to debug just let me know.

Thanks and best regards,
Fabian

**Comment by nsinenian** [comment] 2015-05-20 04:19
This issue (the login part) seems to be occurring with both FreeBSD targets and the Linux LIO target (but not the linux IET target).  Some VMs have been set up to try to get to the bottom of this.  Can you provide a packet dump (e.g., tcpdump or wireshark) during the login process?  It would be helpful to see the raw bytes.

The other problems you've discovered are known issues (i.e., daemon hanging).  Once a failure occurs the daemon doesn't recover gracefully.  A fix is in the works but it's not the root cause of what you've observed.

**Comment by nsinenian** [comment] 2015-06-11 14:59
The login issue should now be fixed (along with several other fixes, including the name issue you brought up).  Please keep each issue specific enough so that we can close them as they are individually fixed.

**Closed** 2015-10-27 17:44 UTC
Labels: bug
