### ISSUE TITLE
Mountain Lion build fails.

### ISSUE THREAD

**Issue by since19861019** [iscsi-osx/iSCSIInitiator#33] opened 2016-02-02 03:08 UTC
I needed to add some conditional defines to build for Mountain Lion.
1. As errno_t is not defined, the code below must be defined somewhere ( I did it in iSCSITypesShared.h )

```
#if MAC_OS_X_VERSION_MIN_REQUIRED <= MAC_OS_X_VERSION_10_8
typedef int errno_t;
#endif
```

2. Some string constants need to be defined (I did it in iSCSIIORegistry.h).
```
#define kIOPropertyiSCSIQualifiedNameKey "iSCSI Qualified Name"
#if MAC_OS_X_VERSION_MIN_REQUIRED <= MAC_OS_X_VERSION_10_8
#define kIOPropertyProtocolCharacteristicsKey	"Protocol Characteristics"
#define kIOPropertySCSIDomainIdentifierKey	"SCSI Domain Identifier"
#define kIOPropertySCSITargetIdentifierKey	"SCSI Target Identifier"
#define kIOPropertySCSILogicalUnitNumberKey	"SCSI Logical Unit Number"

#define	kIOBSDNameKey	"BSD Name"
#define	kIOMediaSizeKey	"Size"
#define kIOMediaPreferredBlockSizeKey	"Preferred Block Size"
#endif
```

3. "com.apple.kpi.mach" in Info.plist must be set to 12.6 or smaller.

**Comment by BjoKaSH** [comment] 2016-02-02 09:57
Set is strange.  If I am not mistaken, then C99 explicitly defines ```errno``` as type ```int``` as all the prototypes in ```man 3 perror``` show or ```man 2 intro``` shows.  That is for userland.

For kernel land it seems only the ```buf_*``` functions defined in /usr/include/sys/buf.h use a typedef'ed ```errno_t``` (I couldn't find a man page describing these functions, so I __guess__ they are not to be used in portable userland code).

In Mavericks (one above "Mountain Lion") the relevant typedef is in ```/usr/include/sys/_types/_errno_t.h``` which gets include from ```/usr/include/sys/errno.h``` under some obscure ```#if ...``` and from ```/usr/include/types.h``` if either ```_POSIX_C_SOURCE``` is **not** defined or ```_DARWIN_C_SOURCE``` **is** defined.

In Snow Leopard (two below "Mountain Lion") the relevant typedef is in ```/usr/include/sys/kernel_types.h```.

So I would suggest to conditionally ```#include <sys/kernel_types.h>``` instead of directly typedef'ing.

**Comment by nsinenian** [comment] 2016-02-12 13:36
This is very strange. The string constants are defined in the appropriate headers in Mountain Lion. See, for example, "kIOPropertyProtocolCharacteristicsKey" on Apple's [open-source site for OS X 10.8](http://www.opensource.apple.com/source/IOStorageFamily/IOStorageFamily-155.5/IOStorageProtocolCharacteristics.h). Many of the other keys are also defined there.

Are you sure that the issue isn't your Xcode installation or environment? It would be good to verify this on another Mountain Lion machine. Alternatively, the issue could have to do wth the project settings, but the file and the definitions are definitely there, so we shouldn't need to redefine them here.

**Comment by since19861019** [comment] 2016-02-13 08:12
I reinstalled XCode (5.1.1) , which bndles 10.8 & 10.9 SDK, and started build from newly acquired source files.
I changed SDK/deployment target to 10.8 and checked the build:

iSCSIInitiator.kext build succeeds.
iscsid - need to #include <sys/kernel_types.h> for errno_t.
iscsictl - need to fix aopenclient,  #include <sys/kernel_types.h>  and <IOKit/storage/IOStorageDeviceCharacteristics.h>,<IOKit/storage/IOMedia.h>, .. to build.

Do I have to do anything other than switching BASE SDK and deployment target ?

**Comment by nsinenian** [comment] 2016-02-13 08:19
What is "aopenclient"? And did you have to #define anything to build iscsid/iscsictl?

**Comment by since19861019** [comment] 2016-02-13 09:55
Sorry, it is `aslclient`.

I did not have to #define anything, but I had to add some #includes.

**Comment by nsinenian** [comment] 2016-02-13 17:12
The `aslclient` issue was resolved in the develop branch (I assume you're using master). I'm glad to see that the other #defines were not necessary (e.g., kIOPropertyProtocolCharacteristicsKey). As for the #includes for errno_t, I agree there's an issue, the fix however may be as simple as changing the compiler language version settings. Please see this [stackoverflow article](http://stackoverflow.com/questions/24206989/error-use-of-undeclared-identifier-errno-t) for an explanation of the issue. Please try using changing the 'C Language Dialect' under each of the target's build settings in Xcode. You should see options like c11, gnu11, c99, gnu99, etc. On my machine, it doesn't make a difference, but given that you're using an older SDK you may see a difference. Let me know if that works, otherwise we'll incorporate the #include into the code base.

**Comment by since19861019** [comment] 2016-02-14 04:43
I found compiler dialect settings has no effect, but I also found,
10.9 SDK: `usr/include/sys/errno.h` has  #include `<sys/_types/_errno_t.h>`
10.8 SDK: no correspoding #include/#defines
So, in order to build on <= 10.8, `errno_t` must be explicitly defined as I did in my first post ( maybe in `iSCSITypes.h` ?) as `errno_t` in not defined in userland.

As for the other string properties, I needed to add
```
#include <IOKit/IOBSD.h>
#include <IOKit/storage/IOMedia.h>
#include <IOKit/storage/IOStorageDeviceCharacteristics.h>
```
in iSCSICtl.m.
The names defined in IOKit/scsi are found, but those under IOKit/storage are not.

**Comment by nsinenian** [comment] 2016-02-14 05:00
Ok, it makes more sense to add the #includes to iSCSIIORegistry, which is included by iscsictl.m. As for the errno_t I'll it's been added to iSCSITypes.h.

Please confirm that the develop branch now works and I'll close this out.

**Comment by since19861019** [comment] 2016-02-14 05:41
iSCSITypes.h is not included in iscsictl, so I moved the errno_t typedef to iSCSITypesShared.h, and compilation succeeded.
Only remaining problem is link errors in building iscsctl like:
```
Undefined symbols for architecture x86_64:
  "_DADiskCreateFromIOMedia", referenced from:
      _iSCSIDAUnmountApplierFunc in iSCSIDA.o
      _iSCSIDAMountApplierFunc in iSCSIDA.o
  "_DADiskMount", referenced from:
      _iSCSIDAMountApplierFunc in iSCSIDA.o
  "_DADiskUnmount", referenced from:
...
```
which does not occur when BASE SDK/target is 10.9 with the same Xcode.

**Comment by nsinenian** [comment] 2016-02-14 06:07
Unfortunately I can’t troubleshoot this myself given that I don’t have this version of OS X available to me. If you look at the build targets you’ll see that iscsid has some frameworks listed under “Build Phases” and “Link Binary With Libraries”. Those same frameworks are not listed under the iscsictl target. Please add them and see if that makes a difference for 10.8. It doesn’t seem to do much for higher versions.

**Comment by since19861019** [comment] 2016-02-14 09:34
Adding 2 Frameworks (IOKit and DiskArbitration),  the build succeeded.
Thanks!

**Comment by nsinenian** [comment] 2016-02-14 09:59
Excellent. I've made similar changes to develop, should work now.

**Closed by nsinenian** 2016-02-14 09:59 UTC
Labels: wontfix
