### ISSUE TITLE
Auto-login not working

### ISSUE THREAD

**Issue by vlc1** [iscsi-osx/iSCSIInitiator#56] opened 2016-08-16 21:40 UTC
Hi Nareg,

first of, thanks for this very nice work, I'm using your code on a NAS and so far it's working great.

The only trouble I'm having is with the auto-login: for some reason, when I boot El Capitan, the daemon does not seem to login. It seems working however, since
```
$ sudo launchctl list | grep iscsi
81	0	com.github.iscsi-osx.iscsid
```
and when I list the target-config auto-login is indeed enabled:
```
$ iscsictl list target-config <target>
iqn.*** <inactive, static>
	auto-login: enabled
	Configuration:
		MaxConnections (1)
		ErrorRecoveryLevel (0)
		HeaderDigest (none)
		DataDigest (none)
	Authentication: none
		CHAP-name
		CHAP-secret <unspecified>
	192.168.0.18 <inactive, port 3260, interface default>
```

I should mention that manual login/logout are working fine, and that I'm using the master branch of the repository (which matches the latest release if I'm not mistaken).

Any input will be very much appreciated, thanks!

V.

**Comment by nsinenian** [comment] 2016-08-17 05:09
@vlc1 Hi, please try the develop branch. Significant modifications were made to auto-login and connection persistence (e.g., after waking up from sleep) to address these issues, but they haven't made it into the master yet. Please try the develop branch and tell me if you still have problems.

**Comment by zazard** [comment] 2016-08-17 11:22
Hello,

I did have this issue also, but didn't bother reporting since I didn't really plan to use this feature.
I confirm that on the develop branch it seems to be fixed.

**Comment by vlc1** [comment] 2016-08-17 20:41
@zazard Ok hopefully I can get things to work as well.

@nsinenian The develop branch is throwing an error when setting the one-way CHAP secret while configuring the initiator (the error does not occur in the master branch):
```
$ iscsictl modify initiator-config -CHAP-secret
Enter shared secret:
Verify shared secret:
iscsictl: No valid options have been specified.
```

Any idea why that might be?

**Comment by nsinenian** [comment] 2016-08-20 06:58
@vlc1 The -CHAP-secret issue is now fixed on develop.

@zazard I'm going to close this out since you confirmed that it does work (on develop, not master). I hope to merge these changes into master soon for the next release.

**Closed by nsinenian** 2016-08-20 06:58 UTC
